# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "Gemfile", "Gemfile.lock"] # files to exclude
highlighter: true
github:
  is_user_page: false
  is_project_page: true
  owner_url: "https://github.com/qifun"
  owner_gravatar_url: "https://github.com/qifun.png"
  owner_url: "https://github.com/qifun"
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 岂凡技术小报

title: 小报
description: 岂凡技术小报
bitbucket: qforce
email: yangbo@qifun.com

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
encoding: utf-8
timezone: CN
permalink: /:year/:month/:day/:title
gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap

baseurl: /newspaper
